---
title: "Homework 2"
output: github_document
---

```{r, message = FALSE, echo = FALSE}
library(tidyverse)
library(readxl)
library(haven)
```

# Problem 1

## Loading Data and cleaning up
```{r}
nyc_transit = read_csv('data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv', na = "") %>% 
  janitor::clean_names() %>% 
      pivot_longer(
      cols = route1:route11,
      names_to = "route_number",
      values_to = "route_name",
      values_transform = list(route_name = as.character),
      names_prefix = "route"
    ) %>% 
  mutate(
    entry = case_match(
    entry,
    "YES" ~ TRUE,
    "NO" ~ FALSE
  )) %>% 
  select("line","station_name","station_latitude","station_longitude","route_number","route_name", "entry", "vending", "entrance_type", "ada") 

```

Questions answering some of the data *change to inline in R
```{r}
distinct(nyc_transit, station_name)

ada_compliant = nyc_transit %>% 
  filter(ada == TRUE)

distinct(ada_compliant, station_name)

no_vending = nyc_transit %>% 
  filter(vending == "NO")

sum(no_vending$entry == TRUE)/nrow(no_vending)

```
1. There are 356 distinct stations.
2. There are 73 stations that are ADA compliant
3. The proportion of station/entrances without vending that allow entrance is 0.377.

# Problem 2
```{r}
mr = read_excel("data/202409 Trash Wheel Collection Data.xlsx", sheet = "Mr. Trash Wheel", skip = 1) %>% janitor::clean_names() %>% 
  select(dumpster:homes_powered) %>% 
  filter(dumpster != "NA") %>% 
  mutate(sports_balls = as.integer(sports_balls),
         type = "mr_trash",
         year = as.numeric(year)
  )

professor = read_excel("data/202409 Trash Wheel Collection Data.xlsx", sheet = "Professor Trash Wheel", skip = 1) %>% janitor::clean_names() %>%
  filter(dumpster != "NA") %>% 
  mutate(type = "professor_trash")

gwynnda = professor_trash_wheel = read_excel("data/202409 Trash Wheel Collection Data.xlsx", sheet = "Gwynnda Trash Wheel", skip = 1) %>% janitor::clean_names() %>%
  filter(dumpster != "NA") %>% 
  mutate(type = "gwynnda")


trash_wheel =
  bind_rows(
    mr, professor, gwynnda) %>% 
  janitor::clean_names()

summary(trash_wheel)
```
Description of Trash Wheel data set


# Problem 3
```{r}
bakers = read_csv("data/gbb_datasets/bakers.csv") %>% 
  janitor::clean_names() %>% 
  mutate(
    first_name = sub("(\\w+\\.?).*", "\\1", baker_name)
  )

bakes = read_csv("data/gbb_datasets/bakes.csv", na = c("N/A" , "UNKNOWN", "", "Unknown")) %>%
  janitor::clean_names() %>% 
  mutate(
    baker = str_replace_all(baker,'"Jo"', "Jo")
  )


results = read_csv("data/gbb_datasets/results.csv", na = "NA", skip = 2) %>% 
  janitor::clean_names() %>% 
  mutate(
    baker = str_replace_all(baker,'"Jo"', "Jo")
  )

```
```{r}
missing_bakes = anti_join(bakers,bakes, by = c("first_name" = "baker", "series"))

missing_results = anti_join(bakers, results, by = c("first_name" = "baker", "series"))

missing_bakes_results = anti_join(bakers,bakes, by = c("first_name" = "baker", "series"))
```

Merging Dataset
```{r}
bake_off = left_join(bakes, results, by = c("baker" = "baker", "series" = "series", "episode" = "episode"))%>% 
  left_join(., bakers, by = c("baker" = "first_name", "series" = "series")) %>% relocate(baker_name, baker_age, baker_occupation, hometown, series, episode, signature_bake, show_stopper, technical, result) %>% 
  arrange(series, episode, baker_name)


#write.csv(bake_off, file="data/gbb_datasets/bake_off.csv")
```

```{r}
winners =
  results %>% 
  filter(
    series <= 10, series >= 5) %>% 
  filter(
    result %in% c("WINNER", "STAR BAKER")
    ) %>% 
  select(series, episode, baker, result) %>% 
  pivot_wider(
    names_from = series,
    values_from = baker
  )

head(winners)
```


```{r}
viewers = read_csv("data/gbb_datasets/viewers.csv", na = "NA") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    cols = series_1:series_10,
    names_to = "series",
    values_to = "viewership",
    names_prefix = "series_"
  ) %>% 
  mutate(
    series = as.integer(series)
  ) %>% 
  arrange(series, episode)

head(viewers, 10)

viewers %>% 
  filter(series == "1") %>% 
  summarise(mean(viewership, na.rm = TRUE))

viewers %>% 
  filter(series == "5") %>% 
  summarise(mean(viewership, na.rm = TRUE))
```


